# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
       cache_photos:
          web_path:
            # use %kernel.project_dir%/web for Symfony prior to 4.0.0
            web_root: "%kernel.project_dir%/public"
            cache_prefix: "media/cache"

    cache: cache_photos

    filter_sets: 
        
        polar:
            quality: 75
            filters:
                scale:
                    dim: [250, 250]

        carre: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [200, 200] # Taille de l'image de sortie
                    mode: inset # Découpage de l'image

        bg:
            quality: 75
            filters:
                scale: # Filtre "Thumbnail"
                    dim: [355, 277] # Taille de l'image de sortie
                background: 
                    color: '#ffffff'
                    size: [355, 277]
                    position: center

        show:
            quality: 85
            filters:
                scale:
                    dim: [1019, 610]
                background:
                    color: '#ffffff'
                    size: [1019,610]
                    position: center

        # photo_profil_nav:


        # photo_profil_bg:

        # photo_profil: