# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
       cache_photos:
          web_path:
            # use %kernel.project_dir%/web for Symfony prior to 4.0.0
            web_root: "%kernel.project_dir%/public"
            cache_prefix: "media/cache"

    cache: cache_photos

    filter_sets: 


        bg:
            quality: 75
            filters:
                scale: # Filtre "Thumbnail"
                    dim: [355, 277] # Taille de l'image de sortie
                # background: 
                #     color: '#ffc0cb'
                #     size: [355, 277]
                #     position: center

        show:
            quality: 90
            filters:
                scale:
                    dim: [1019, 800]
                # background:
                #     color: '#ffffff'
                #     size: [1019,800]
                #     position: center

        photoProfilNav:
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [35, 35] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image

        photo_profil_bg:
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [30, 30] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image

        photo_profil:
            quality: 85
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound

        comment_photo_profil:
            quality: 75
            filters:
                thumbnail:
                    size: [50,50]
                    mode: outbound

        last_photos:
            quality: 75
            filters:
                downscale:
                    max: [100,100]

